# -*- coding: utf-8 -*-
"""
Created on Fri Nov 10 17:30:18 2023

@author: HP
"""
# ----------Step 1: Data exploration with Pandas
# Download the provided dataset
# Use pandas to read the file into a pandas Dataframe.
# Display general information about the dataset.
# Run descriptive analysis on the dataset using the 'describe' function.
# ----------Step 2: Data exploration with ydata-profiling
# Use ydata-profiling to generate a report of the provided dataset.
# Look for missing values in the dataset. You can use the report generated by ydata to identify missing values.
# Examine the correlations between different columns in the dataset. You can use the report generated by ydata to identify correlations.
# Identify any other interesting patterns or insights in the dataset that you can discover through the ydata-profiling report.
# ----------Step 3: Summary
# Write a summary of your findings based on the ydata-profiling report. Be sure to include any interesting patterns or insights you discovered in the dataset.

# ----------Step 1: Data exploration with Pandas-------------


import pandas as pd
import sweetviz as sv
# --------Question_1---------------:
    # Use pandas to read the file into a pandas Dataframe.
data = "C:/Users/HP/Downloads/EDUCATION_ATTAINMENT.csv"
dataset = pd.read_csv(data)
# --------Question_2---------------:
    # Display general information about the dataset.
print(dataset.info())
# --------Question_3---------------:
    # Run descriptive analysis on the dataset using the 'describe' function.
desc_dataset = dataset.describe(include = "all")

# ----------Step 2: Data exploration with ydata-profiling------------


# --------Question_1---------------:
    # Use ydata-profiling to generate a report of the provided dataset.
my_report = sv.analyze(dataset)
my_report.show_html()
# --------Question_2---------------:
    # Look for missing values in the dataset. You can use the report generated by ydata to identify missing values.
missing_values = dataset.isnull().sum().sum()
# --------Question_3---------------:
    # Examine the correlations between different columns in the dataset. You can use the report generated by ydata to identify correlations.
# Examining the correlation between column 0 & 1
corr_1 = dataset.iloc[:, 0].corr(dataset.iloc[:, 1])
# Examining the correlation between column 30 & 11
corr_2 = dataset.iloc[:, 30].corr(dataset.iloc[:, 11])
# Examining the correlation between column 10 & 21
corr_3 = dataset.iloc[:, 10].corr(dataset.iloc[:, 21])
# Examining the correlation between column 33 & 25
corr_4 = dataset.iloc[:, 33].corr(dataset.iloc[:, 25])
# Examining the correlation between column 17 & 15
corr_5 = dataset.iloc[:, 17].corr(dataset.iloc[:, 15])
# Examining the correlation between column 20 & 29
corr_6 = dataset.iloc[:, 20].corr(dataset.iloc[:, 29])
# Identify any other interesting patterns or insights in the dataset that you can discover through the ydata-profiling report.
# --------My Obrevation:
    # from the result shown in the variable explorer, it indicates that the two columns each highly correlated in a positive direction. 
# Write a summary of your findings based on the ydata-profiling report. Be sure to include any interesting patterns or insights you discovered in the dataset.





